#!/usr/bin/env bash

webroot=/var/www/html/dmaonline
target=dmao_dashboard

cd ${webroot}
if [ $? -ne 0 ]
then
	echo "Can't cd to ${webroot}"
	exit 1
fi
ret=$(git pull)
if [[ "${ret}" == "Already up-to-date." ]]
then
	echo "Already up-to-date."
	exit 0
fi
echo "${ret}"

find ${target} -type d -exec chmod a+rx {} \;
find ${target} -type f -exec chmod a+r {} \;
chown -R root:root ${target}

echo "
New DMAOnline release at

	http://lib-ldiv.lancs.ac.uk:8080/dmaonline/dashboard" \
| mutt -s "New DMAOnline release - $(date '+%d/%m/%Y %H:%M')" -- \
j.krug@lancaster.ac.uk \
a.albin-clark@lancaster.ac.uk \
masud.khokhar@lancaster.ac.uk \
h.schwamm@lancaster.ac.uk
